{{- if .Values.kyverno.enabled }}
apiVersion: kyverno.io/v1
kind: ClusterPolicy

metadata:
  name: require-approved-registry

  annotations:
    policies.kyverno.io/title: Require Approved Image Registry
    policies.kyverno.io/category: Supply Chain Security
    policies.kyverno.io/severity: medium
    policies.kyverno.io/description: >-
      Containers must use images from approved registries.

spec:
  validationFailureAction: Enforce

  background: true

  rules:
    - name: validate-image-registry

      match:
        any:
          - resources:
              kinds:
                - Pod

      validate:
        message: "Container images must come from an approved registry."

        anyPattern:
          - spec:
              containers:
                - image: "docker.io/*"

          - spec:
              containers:
                - image: "quay.io/*"

          - spec:
              containers:
                - image: "ghcr.io/*"

          - spec:
              containers:
                - image: "public.ecr.aws/*"

{{- end }}