apiVersion: v1
kind: ServiceAccount

metadata:
  name: backend-service-account
  namespace: production-eks-platform


---

apiVersion: v1
kind: ServiceAccount

metadata:
  name: frontend-service-account
  namespace: production-eks-platform


---

apiVersion: v1
kind: ServiceAccount

metadata:
  name: postgres-service-account
  namespace: production-eks-platform  