services:
  postgres:
    image: postgres:16
    container_name: production-platform-postgres
    restart: unless-stopped

    environment:
      POSTGRES_DB: products_db
      POSTGRES_USER: app_user
      POSTGRES_PASSWORD: app_password

    ports:
      - "5432:5432"

    volumes:
      - postgres_data:/var/lib/postgresql/data

  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile

    container_name: production-platform-backend
    restart: unless-stopped

    ports:
      - "3000:3000"

    environment:
      PORT: 3000
      DB_HOST: postgres
      DB_PORT: 5432
      DB_NAME: products_db
      DB_USER: app_user
      DB_PASSWORD: app_password

    depends_on:
      - postgres

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile

    container_name: production-platform-frontend
    restart: unless-stopped

    ports:
      - "5173:80"

    depends_on:
      - backend

volumes:
  postgres_data: