apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-config
  namespace: {{ .Release.Namespace }}
data:
  PORT: {{ .Values.backend.config.port | quote }}
  DB_HOST: {{ .Values.backend.config.dbHost | quote }}
  DB_PORT: {{ .Values.backend.config.dbPort | quote }}
  DB_NAME: {{ .Values.backend.config.dbName | quote }}
