{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  DB_USER: {{ .Values.secrets.postgres.username | quote }}
  DB_PASSWORD: {{ .Values.secrets.postgres.password | quote }}
{{- end }}