{{- if .Values.secrets.create }}
apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: {{ .Release.Namespace }}
type: Opaque
stringData:
  POSTGRES_DB: {{ .Values.secrets.postgres.database | quote }}
  POSTGRES_USER: {{ .Values.secrets.postgres.username | quote }}
  POSTGRES_PASSWORD: {{ .Values.secrets.postgres.password | quote }}
{{- end }}