apiVersion: apps/v1
kind: StatefulSet

metadata:
  name: postgres
  namespace: production-eks-platform

spec:
  serviceName: postgres-headless

  replicas: 2

  selector:
    matchLabels:
      app: postgres

  template:
    metadata:
      labels:
        app: postgres

    spec:
      securityContext:
        fsGroup: 999

      containers:
        - name: postgres
          image: postgres:16-alpine

          ports:
            - containerPort: 5432
              name: postgres

          env:
            - name: POSTGRES_DB
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_DB

            - name: POSTGRES_USER
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_USER

            - name: POSTGRES_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: postgres-secret
                  key: POSTGRES_PASSWORD


          resources:
            requests:
              cpu: "500m"
              memory: "512Mi"

            limits:
              cpu: "1"
              memory: "1Gi"


          startupProbe:
            exec:
              command:
                - pg_isready
                - -U
                - $(POSTGRES_USER)

            failureThreshold: 30
            periodSeconds: 10


          livenessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - $(POSTGRES_USER)

            initialDelaySeconds: 30
            periodSeconds: 10
            timeoutSeconds: 5
            failureThreshold: 3


          readinessProbe:
            exec:
              command:
                - pg_isready
                - -U
                - $(POSTGRES_USER)

            initialDelaySeconds: 10
            periodSeconds: 5
            timeoutSeconds: 5
            failureThreshold: 3


          volumeMounts:
            - name: postgres-storage
              mountPath: /var/lib/postgresql/data


  volumeClaimTemplates:
    - metadata:
        name: postgres-storage

      spec:
        accessModes:
          - ReadWriteOnce

        resources:
          requests:
            storage: 10Gi